import {
    PiHouseLineDuotone,
    PiBriefcaseDuotone,
    PiTruckDuotone,
    PiUsersDuotone,
    PiBuildingsDuotone,
    PiCalendarDuotone,
    PiMapPinDuotone,
    PiClipboardTextDuotone,
    PiReceiptDuotone,
    PiRepeatDuotone,
    PiHandshakeDuotone,
    PiGearDuotone,
    PiUserCheckDuotone,
    PiShieldCheckDuotone,
    PiDatabaseDuotone,
    PiStackDuotone,
    PiUserCircleDuotone,
    PiPathDuotone,
    PiNotepadDuotone,
    PiBugDuotone,
    PiSignatureDuotone,
    PiIdentificationCardDuotone,
    PiTreeStructureDuotone,
    PiMedalDuotone,
    PiCarProfileDuotone,
    PiMapTrifoldDuotone,
    PiUsersThreeDuotone,
    PiKeyDuotone,
    PiBuildingOfficeDuotone,
    PiPuzzlePieceDuotone,
} from 'react-icons/pi'
import type { JSX } from 'react'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    home:       <PiHouseLineDuotone />,
    briefcase:  <PiBriefcaseDuotone />,
    handshake:  <PiHandshakeDuotone />,
    truck:      <PiTruckDuotone />,
    users:     <PiUsersDuotone />,
    building:  <PiBuildingsDuotone />,
    calendar:  <PiCalendarDuotone />,
    mapPin:    <PiMapPinDuotone />,
    clipboard: <PiClipboardTextDuotone />,
    receipt:    <PiReceiptDuotone />,
    repeat:     <PiRepeatDuotone />,
    settings:   <PiGearDuotone />,
    userCheck:  <PiUserCheckDuotone />,
    shield:     <PiShieldCheckDuotone />,
    database:   <PiDatabaseDuotone />,
    layers:     <PiStackDuotone />,
    userCircle: <PiUserCircleDuotone />,
    path:          <PiPathDuotone />,
    notepad:       <PiNotepadDuotone />,
    bug:           <PiBugDuotone />,
    contract:      <PiSignatureDuotone />,
    idCard:        <PiIdentificationCardDuotone />,
    treeStructure: <PiTreeStructureDuotone />,
    medal:         <PiMedalDuotone />,
    carProfile:    <PiCarProfileDuotone />,
    map:           <PiMapTrifoldDuotone />,
    usersThree:    <PiUsersThreeDuotone />,
    key:           <PiKeyDuotone />,
    office:        <PiBuildingOfficeDuotone />,
    puzzle:        <PiPuzzlePieceDuotone />,
}

export default navigationIcon
