import authRoute from './authRoute'
import type { Routes } from '@/@types/routes'

const listRoute = (path: string, key: string, authority: string[] = []): Routes => ({
    [`/${path}`]: { key, authority },
    [`/${path}/baru`]: { key, authority },
    [`/${path}/[id]`]: { key, authority, dynamicRoute: true },
})

const ADMIN_ONLY = ['manager', 'admin', 'superadmin']

export const protectedRoutes: Routes = {
    '/home': {
        key: 'home',
        authority: [],
    },
    ...listRoute('klien', 'klien'),
    ...listRoute('project', 'project'),
    ...listRoute('penawaran', 'penawaran'),
    '/dashboard-armada': { key: 'dashboard-armada', authority: [] },
    ...listRoute('armada', 'armada'),
    ...listRoute('perawatan-armada', 'perawatan-armada'),
    '/dokumen-armada':   { key: 'dokumen-armada', authority: [] },
    ...listRoute('jenis-perawatan', 'jenis-perawatan'),
    ...listRoute('interval-perawatan', 'interval-perawatan'),
    ...listRoute('sparepart', 'sparepart'),
    ...listRoute('supplier', 'supplier'),
    ...listRoute('pembelian-sparepart', 'pembelian-sparepart'),
    '/pembelian-sparepart/[id]/edit': { key: 'pembelian-sparepart', authority: [], dynamicRoute: true },
    ...listRoute('shift', 'shift'),
    ...listRoute('supir', 'supir'),
    ...listRoute('vendor', 'vendor'),
    ...listRoute('kontrak-vendor', 'kontrak-vendor'),
    ...listRoute('armada-vendor', 'armada-vendor'),
    ...listRoute('supir-vendor', 'supir-vendor'),
    '/evaluasi-vendor': { key: 'evaluasi-vendor', authority: [] },
    ...listRoute('rute', 'rute'),
    '/trip': { key: 'trip', authority: [] },
    '/trip/[id]': { key: 'trip', authority: [], dynamicRoute: true },
    '/penugasan': { key: 'penugasan', authority: [] },
    '/penugasan/[id]': { key: 'penugasan', authority: [], dynamicRoute: true },
    '/jadwal-shift-supir': { key: 'jadwal-shift-supir', authority: [] },
    '/penugasan-vendor': { key: 'penugasan-vendor', authority: [] },
    '/penugasan-vendor/baru': { key: 'penugasan-vendor', authority: [] },
    '/penugasan-vendor/[id]': { key: 'penugasan-vendor', authority: [], dynamicRoute: true },
    ...listRoute('laporan', 'laporan'),
    ...listRoute('faktur', 'faktur'),
    ...listRoute('invoice-vendor', 'invoice-vendor'),
    '/konsolidasi-vendor': { key: 'konsolidasi-vendor', authority: [] },
    '/konsolidasi-klien': { key: 'konsolidasi-klien', authority: [] },
    '/arus-kas': { key: 'arus-kas', authority: [] },
    '/proses-pembayaran': { key: 'proses-pembayaran', authority: [] },
    '/konfigurasi-approval': { key: 'konfigurasi-approval', authority: ['superadmin', 'admin'] },
    ...listRoute('pengguna', 'pengguna', ADMIN_ONLY),
    ...listRoute('peran', 'peran', ADMIN_ONLY),
    ...listRoute('jenis-kendaraan', 'jenis-kendaraan'),
    ...listRoute('lokasi-kantor', 'lokasi-kantor'),
    ...listRoute('lokasi', 'lokasi'),
    ...listRoute('jenis-bbm', 'jenis-bbm'),
    ...listRoute('parameter-bok', 'parameter-bok', ADMIN_ONLY),
    ...listRoute('departemen', 'departemen'),
    ...listRoute('jabatan', 'jabatan'),
    '/struktur-organisasi': { key: 'struktur-organisasi', authority: [] },
    ...listRoute('karyawan', 'karyawan'),
    '/cuti': { key: 'cuti', authority: [] },
    '/absensi': { key: 'absensi', authority: [] },
    '/payroll': { key: 'payroll', authority: [] },
    '/payroll/pengaturan': { key: 'payroll', authority: [] },
    '/payroll/[id]': { key: 'payroll', authority: [], dynamicRoute: true },
    ...listRoute('perusahaan', 'perusahaan', ADMIN_ONLY),
    ...listRoute('menu-admin', 'menu-admin', ADMIN_ONLY),
    '/log-error': { key: 'log-error', authority: [] },
    '/log-error/[id]': { key: 'log-error', authority: [], dynamicRoute: true },
    '/format-kode': { key: 'format-kode', authority: ['superadmin', 'admin'] },
}

export const publicRoutes: Routes = {
    '/': { key: 'landing', authority: [] },
    '/tentang': { key: 'tentang', authority: [] },
    '/layanan': { key: 'layanan', authority: [] },
    '/armada-kami': { key: 'armadaKami', authority: [] },
    '/kontak': { key: 'kontak', authority: [] },
}

export const authRoutes = authRoute
